### ISSUE TITLE
శ తర్వాత వచ్చే అక్షరాలు ఎడంగా ఉండిపోతున్నాయి

### ISSUE THREAD

**Issue by veeven** [appajid/ponnala#2]
![శ తర్వాత అక్షరాలు](https://user-images.githubusercontent.com/6792988/99878905-98497200-2c2e-11eb-9345-7fd29af8d6f0.png)
![చిత్రము](https://user-images.githubusercontent.com/6792988/99878809-ff1a5b80-2c2d-11eb-9c4f-04767a148394.png)

**Comment by appajid** [comment]
This got rectified in new version.
